name: dart_executor
publish_to: none

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  intl4x:
    git:
      url: git@github.com:dart-lang/i18n.git
      path: pkgs/intl4x
      ref: intl4x-v0.9.2
  pubspec_lock_parse: ^2.2.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.2
